version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
     - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app/merch_project
    restart: always
#    volumes:
##      - static_volume:/app/static
#      - static_volume:/app/merch_project/staticfiles
#      - ./staticfiles:/app/staticfiles


  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      env_file:
#        - .env
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    restart: always
    volumes:
#      - ./etc/nginx:/etc/nginx
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - .:app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
#  static_volume:
