version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    ports:
     - "8080:8080"
#     - "5678:5678"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    working_dir: /app/merch_project
    restart: always
    volumes:
    - static_volume:/app/merch_project/staticfiles
#      - static_volume:/app/merch_project/staticfiles
#      - ./staticfiles:/app/staticfiles


  db:
    image: postgres:16
    container_name: db
    restart: always
#    environment:
    env_file:
      - .env
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/cache:/data

  nginx:
    image: nginx:latest
    restart: always
    links:
      - web
#    volumes:
#      - ./etc/nginx:/etc/nginx
#      - /etc/nginx/nginx.conf:merch-store/etc/nginx
#      - /merch-store/etc/nginx:/etc/nginx
#      - .:app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
